[package]
name = "vulkan-tutorial"
version = "0.3.0"
edition = "2024"
repository = "https://github.com/FrightenedFoxCN/vulkan-tutorial.git"

[dependencies]
vulkano = "0.34.0"
vulkano-shaders = "0.34.0"
image = "0.24"

[[bin]]
name = "compute_shader"
path = "compute_pipeline/src/main.rs"
